#!/bin/bash
####################
#
# Default variables
#
####################

HTTP_PROXY=
HTTPS_PROXY=

IP=`hostname -i`
MACHINE=`hostname -s`
FQDN=`hostname -f`

if [[ $FQDN =~ .*.internal$ ]]; then
    MACHINE="%.internal"
fi

MASK=24

TIMEZONE=Australia/Melbourne

